services:
  # ML Pipeline service - запускается только по требованию
  ml-pipeline:
    build: ./ml
    container_name: hackaton-ml-pipeline
    volumes:
      - ./backend:/out
      - ml-pipeline-storage:/app/local_storage
    environment:
      - OMP_NUM_THREADS=4
      - PYTHONUNBUFFERED=1

  backend:
     build: ./backend
     container_name: hackaton-backend
     command: python -m uvicorn main:application --host 0.0.0.0
     ports:
       - "8000:8000"
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock
       - ./backend:/app
     environment:
       - ML_PIPELINE_SERVICE=ml-pipeline

volumes:
  ml-pipeline-storage:
    driver: local
